version: "3.8"

volumes:
  migrations:
  app-volume:

networks:
  subalogue.network:

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SUBALOGUE_ENV=development
    volumes:
      - .:/go/src/app
    depends_on:
      - db
    networks:
      - "subalogue.network"
    volumes:
      - migrations:/db/migrations
  db:
    image: postgres:13
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - "subalogue.network"
