version: "3.8"

volumes:
  dist:

networks:
  net:

secrets:
  shiftingphotons.dev.crt:
    external: true
  shiftingphotons.dev.key:
    external: true
  nginx.conf:
    external: true
  env.production:
    external: true

services:
  nginx:
    image: nginx:latest
    command: sh -c "exec nginx -g 'daemon off;'"
    secrets:
      - shiftingphotons.dev.key
      - shiftingphotons.dev.crt
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
    volumes:
      - dist:/etc/nginx/html
    ports:
      - "443:443"
    networks:
      - "net"
  api:
    image: shiftingphotons/subalogue:latest
    command: bash -c "go build . && ./subalogue"
    secrets:
      - source: env.production
        target: /go/src/app/.env.production
    deploy:
      replicas: 1
    environment:
      - SUBALOGUE_ENV=production
    networks:
      - "net"
  app:
    image: shiftingphotons/subalogue-client:latest
    deploy:
      replicas: 1
    networks:
      - "net"
    volumes:
      - dist:/app/dist
  db:
    image: postgres:13
    deploy:
      replicas: 1
    networks:
      - "net"
    env_file:
      - .env.production
