version: "3.8"
services:
  nginx:
    image: nginx
    build: ./nginx/
    # restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app-volume:/etc/nginx/html/
    depends_on:
      - api
      - app
    networks:
      - "api.network"
  api:
    image: shiftingphotons/subalogue:latest
    env_file:
      - .env.production
    depends_on:
      - db
    networks:
      - "api.network"
    volumes:
      - api_migrations:/go/src/app/db/migrations
  app:
    image: shiftingphotons/subalogue_client:latest
    networks:
      - "api.network"
    volumes:
      - app-volume:/app/dist
  db:
    image: postgres:13
    networks:
      - "api.network"
    env_file:
      - .env.production
  migrate:
    image: migrate/migrate
    command: ["-database", "${DATABASE_URL}", "-path", "migrations", "up"]
    volumes:
      - api_migrations:/migrations
    depends_on:
      - db
    networks:
      - "api.network"

volumes:
  api_migrations:
  app-volume:

networks:
  api.network:
