version: "3.8"

networks:
  subalogue.network:

services:
  api:
    build: .
    command: reflex -r '\.go$$' -s -- sh -c 'go build . && ./subalogue'
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    environment:
      - SUBALOGUE_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - "subalogue.network"
  db:
    image: postgres:13
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5433:5423
    networks:
      - "subalogue.network"
    environment:
      - POSTGRES_USER=subalogue
      - POSTGRES_PASSWORD=subalogue
      - POSTGRES_DB=subalogue_development
