version: "3.8"
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=subalogue
      - POSTGRES_PASSWORD=subalogue
      - POSTGRES_DB=subalogue_development
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/go/src/app
    depends_on:
      - db
  migrate:
    image: migrate/migrate
    command: ["-database", "${DATABASE_URL}", "-path", "/migrations", "up"]
    volumes:
      - $PWD/db/migrations:/migrations
    depends_on:
      - db

