version: "3.8"
services:
  nginx:
    image: nginx
    build: ./nginx/
    restart: always
    ports:
      - "80:80"
    volumes:
      - app-volume:/etc/nginx/html/
    depends_on:
      - api
      - app
    networks:
      - "api.network"
  api:
    image: shiftingphotons/subalogue:latest
    env_file:
      - .env.production
    depends_on:
      - db
    networks:
      - "api.network"
  app:
    image: shiftingphotons/subalogue_client:latest
    networks:
      - "api.network"
    volumes:
      - app-volume:/app/dist
  db:
    image: postgres:13
    env_file:
      - .env.production
    networks:
      - "api.network"

volumes:
  app-volume:

networks:
  api.network:
