// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type Subscription struct {
	ID     int32
	Name   string
	UserID int32
	Price  int32
}

type User struct {
	ID       int32
	Username string
}
