// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Subscription struct {
	ID     int32
	Name   string
	UserID sql.NullInt32
	Price  int32
}

type User struct {
	ID       int32
	Username string
}
