// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type Subscription struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	UserID int32  `json:"user_id"`
	Price  int32  `json:"price"`
	Url    string `json:"url"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
}
