// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateUser(ctx context.Context, username string) (User, error)
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (Subscription, error)
	FindUserByUsername(ctx context.Context, username string) (User, error)
	GetSubscription(ctx context.Context, arg GetSubscriptionParams) (Subscription, error)
	ListSubscriptions(ctx context.Context, userID int32) ([]Subscription, error)
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error)
}

var _ Querier = (*Queries)(nil)
